// Generated from the backend runtime OpenAPI; do not edit.
export const backendRoutes = [
  [
    "GET",
    "/api/v1/alerts"
  ],
  [
    "POST",
    "/api/v1/alerts/{alert_id}/acknowledgement"
  ],
  [
    "POST",
    "/api/v1/missions/{mission_id}/conversations"
  ],
  [
    "GET",
    "/api/v1/missions/{mission_id}/conversations"
  ],
  [
    "POST",
    "/api/v1/conversations/{conversation_id}/messages"
  ],
  [
    "GET",
    "/api/v1/conversations/{conversation_id}/messages"
  ],
  [
    "GET",
    "/api/v1/agent-runs/{run_id}"
  ],
  [
    "POST",
    "/api/v1/agent-runs/{run_id}/resume"
  ],
  [
    "POST",
    "/api/v1/agent-runs/{run_id}/cancel"
  ],
  [
    "PATCH",
    "/api/v1/conversations/{conversation_id}/followup"
  ],
  [
    "GET",
    "/api/v1/stores/{store_id}/agent-knowledge"
  ],
  [
    "POST",
    "/api/v1/stores/{store_id}/agent-knowledge"
  ],
  [
    "GET",
    "/api/v1/agent-runs/{run_id}/events"
  ],
  [
    "GET",
    "/api/v1/agent-runs/{run_id}/events/stream"
  ],
  [
    "GET",
    "/api/v1/agent-runs/{run_id}/evidence"
  ],
  [
    "GET",
    "/api/v1/dashboard"
  ],
  [
    "GET",
    "/api/v1/missions/{mission_id}/timeline"
  ],
  [
    "GET",
    "/api/v1/sales"
  ],
  [
    "GET",
    "/api/v1/sales/summary"
  ],
  [
    "GET",
    "/api/v1/actions"
  ],
  [
    "GET",
    "/api/v1/inbounds"
  ],
  [
    "GET",
    "/api/v1/ledger-entries"
  ],
  [
    "POST",
    "/api/v1/plans/{plan_id}/decision"
  ],
  [
    "GET",
    "/api/v1/actions/{action_id}"
  ],
  [
    "POST",
    "/api/v1/plans/{plan_id}/revision"
  ],
  [
    "GET",
    "/api/v1/me"
  ],
  [
    "GET",
    "/api/v1/stores"
  ],
  [
    "GET",
    "/health/live"
  ],
  [
    "GET",
    "/health/ready"
  ],
  [
    "GET",
    "/api/v1/monitoring/status"
  ],
  [
    "GET",
    "/api/v1/job-runs/{job_run_id}"
  ],
  [
    "GET",
    "/api/v1/catalog"
  ],
  [
    "POST",
    "/api/v1/missions"
  ],
  [
    "GET",
    "/api/v1/missions"
  ],
  [
    "GET",
    "/api/v1/missions/{mission_id}"
  ],
  [
    "POST",
    "/api/v1/missions/{mission_id}/control"
  ],
  [
    "PATCH",
    "/api/v1/missions/{mission_id}/schedule"
  ],
  [
    "POST",
    "/api/v1/missions/{mission_id}/checks"
  ],
  [
    "GET",
    "/api/v1/missions/{mission_id}/plans"
  ],
  [
    "GET",
    "/api/v1/plans/{plan_id}"
  ],
  [
    "POST",
    "/api/v1/stores/{store_id}/documents"
  ],
  [
    "GET",
    "/api/v1/stores/{store_id}/documents"
  ],
  [
    "GET",
    "/api/v1/documents/{document_id}"
  ],
  [
    "PATCH",
    "/api/v1/documents/{document_id}"
  ],
  [
    "POST",
    "/api/v1/documents/{document_id}/versions"
  ],
  [
    "GET",
    "/api/v1/documents/{document_id}/versions"
  ],
  [
    "GET",
    "/api/v1/documents/{document_id}/versions/{version_id}"
  ],
  [
    "GET",
    "/api/v1/documents/{document_id}/versions/{version_id}/content"
  ],
  [
    "POST",
    "/api/v1/documents/{document_id}/control"
  ],
  [
    "POST",
    "/api/v1/documents/{document_id}/versions/{version_id}/index-jobs"
  ],
  [
    "GET",
    "/api/v1/documents/{document_id}/index-jobs/{request_id}"
  ],
  [
    "POST",
    "/api/v1/documents/{document_id}/index-jobs/{request_id}/retry"
  ],
  [
    "POST",
    "/api/v1/documents/{document_id}/publications"
  ],
  [
    "POST",
    "/api/v1/work-items"
  ],
  [
    "GET",
    "/api/v1/work-items"
  ],
  [
    "GET",
    "/api/v1/work-items/{item_id}"
  ],
  [
    "POST",
    "/api/v1/work-items/{item_id}/messages"
  ],
  [
    "POST",
    "/api/v1/missions/{mission_id}/work-item"
  ],
  [
    "POST",
    "/api/v1/work-items/{item_id}/mission"
  ],
  [
    "POST",
    "/api/v1/work-items/{item_id}/control"
  ],
  [
    "POST",
    "/dev/v1/scenarios"
  ],
  [
    "POST",
    "/dev/v1/scenarios/{run_id}/advance"
  ]
] as const
