"""missions planning"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0003_missions_planning"
down_revision = "0002_business_state"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inbound_items",
        sa.Column("action_id", sa.String(length=128), nullable=False),
        sa.Column("sku_id", sa.String(length=128), nullable=False),
        sa.Column("store_id", sa.String(length=128), nullable=False),
        sa.Column("ordered_qty", sa.BigInteger(), nullable=False),
        sa.Column("received_qty", sa.BigInteger(), nullable=False),
        sa.Column("expected_arrival_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "ordered_qty > 0 AND received_qty >= 0 AND received_qty <= ordered_qty",
            name=op.f("ck_inbound_items_quantities"),
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
        ),
        sa.PrimaryKeyConstraint("action_id", "sku_id", name=op.f("pk_inbound_items")),
    )
    op.create_index(op.f("ix_inbound_items_store_id"), "inbound_items", ["store_id"], unique=False)
    op.create_table(
        "missions",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("store_id", sa.String(length=128), nullable=False),
        sa.Column("sku_id", sa.String(length=128), nullable=False),
        sa.Column("objective", sa.String(length=2000), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("mission_version", sa.BigInteger(), nullable=False),
        sa.Column("policy", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("policy_version", sa.String(length=128), nullable=False),
        sa.Column("current_plan_id", sa.String(length=128), nullable=True),
        sa.Column("current_action_id", sa.String(length=128), nullable=True),
        sa.Column("completion_criteria", sa.String(length=256), nullable=False),
        sa.Column("plan_counter", sa.BigInteger(), nullable=False),
        sa.Column("recheck_required", sa.Boolean(), nullable=False),
        sa.Column("manual_check_requested", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('ACTIVE','PAUSED','COMPLETED','CANCELLED')", name=op.f("ck_missions_status")
        ),
        sa.CheckConstraint(
            "mission_version >= 1 AND plan_counter >= 0", name=op.f("ck_missions_versions")
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_missions")),
    )
    op.create_index("ix_missions_page", "missions", ["store_id", "created_at", "id"], unique=False)
    op.create_index(
        "uq_missions_open_scope",
        "missions",
        ["store_id", "sku_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('ACTIVE','PAUSED')"),
    )
    op.create_table(
        "mission_timeline",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("mission_id", sa.String(length=128), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("summary", sa.String(length=2000), nullable=False),
        sa.Column("actor_type", sa.String(length=16), nullable=False),
        sa.Column("actor_id", sa.String(length=128), nullable=True),
        sa.Column("references", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["missions.id"],
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mission_timeline")),
    )
    op.create_index(
        op.f("ix_mission_timeline_mission_id"), "mission_timeline", ["mission_id"], unique=False
    )
    op.create_table(
        "plans",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("mission_id", sa.String(length=128), nullable=False),
        sa.Column("plan_version", sa.BigInteger(), nullable=False),
        sa.Column("state_version", sa.BigInteger(), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('PENDING_APPROVAL','APPROVED','REJECTED','SUPERSEDED','EXPIRED')",
            name=op.f("ck_plans_status"),
        ),
        sa.CheckConstraint(
            "plan_version >= 1 AND state_version >= 1", name=op.f("ck_plans_versions")
        ),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["missions.id"],
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plans")),
        sa.UniqueConstraint("mission_id", "plan_version", name=op.f("uq_plans_mission_id")),
    )
    op.create_index("ix_plans_page", "plans", ["mission_id", "created_at", "id"], unique=False)
    op.create_table(
        "schedules",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("mission_id", sa.String(length=128), nullable=False),
        sa.Column("job_type", sa.String(length=32), nullable=False),
        sa.Column("trigger", sa.String(length=20), nullable=False),
        sa.Column("interval_seconds", sa.BigInteger(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "interval_seconds BETWEEN 5 AND 3600 AND version >= 1",
            name=op.f("ck_schedules_valid_schedule"),
        ),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["missions.id"],
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedules")),
        sa.UniqueConstraint("mission_id", name=op.f("uq_schedules_mission_id")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("schedules")
    op.drop_index("ix_plans_page", table_name="plans")
    op.drop_table("plans")
    op.drop_index(op.f("ix_mission_timeline_mission_id"), table_name="mission_timeline")
    op.drop_table("mission_timeline")
    op.drop_index(
        "uq_missions_open_scope",
        table_name="missions",
        postgresql_where=sa.text("status IN ('ACTIVE','PAUSED')"),
    )
    op.drop_index("ix_missions_page", table_name="missions")
    op.drop_table("missions")
    op.drop_index(op.f("ix_inbound_items_store_id"), table_name="inbound_items")
    op.drop_table("inbound_items")
    # ### end Alembic commands ###
