"""alerts_history"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0004_alerts_history"
down_revision = "0003_missions_planning"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alerts",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("store_id", sa.String(length=128), nullable=False),
        sa.Column("mission_id", sa.String(length=128), nullable=False),
        sa.Column("sku_id", sa.String(length=128), nullable=False),
        sa.Column("scope_key", sa.String(length=64), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("summary", sa.String(length=2000), nullable=False),
        sa.Column("facts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("state_version", sa.BigInteger(), nullable=True),
        sa.Column("related_plan_id", sa.String(length=128), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acknowledged_by", sa.String(length=128), nullable=True),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(status='RESOLVED') = (resolved_at IS NOT NULL)", name=op.f("ck_alerts_resolution")
        ),
        sa.CheckConstraint(
            "severity IN ('INFO','WARNING','CRITICAL')", name=op.f("ck_alerts_severity")
        ),
        sa.CheckConstraint(
            "status IN ('OPEN','ACKNOWLEDGED','RESOLVED')", name=op.f("ck_alerts_status")
        ),
        sa.CheckConstraint(
            "type IN ('STOCKOUT_RISK','CASH_CONSTRAINT','ACTION_EXCEPTION','DATA_STALE')",
            name=op.f("ck_alerts_type"),
        ),
        sa.CheckConstraint(
            "state_version IS NULL OR state_version >= 1", name=op.f("ck_alerts_version")
        ),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["missions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
    )
    op.create_index("ix_alerts_mission", "alerts", ["mission_id"], unique=False)
    op.create_index("ix_alerts_page", "alerts", ["store_id", "first_seen_at", "id"], unique=False)
    op.create_index(
        "ix_alerts_status", "alerts", ["store_id", "status", "last_seen_at"], unique=False
    )
    op.create_index(
        "uq_alerts_active_scope",
        "alerts",
        ["scope_key"],
        unique=True,
        postgresql_where=sa.text("status IN ('OPEN','ACKNOWLEDGED')"),
    )
    op.create_index(
        "ix_mission_timeline_page",
        "mission_timeline",
        ["mission_id", "created_at", "id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_mission_timeline_page", table_name="mission_timeline")
    op.drop_index(
        "uq_alerts_active_scope",
        table_name="alerts",
        postgresql_where=sa.text("status IN ('OPEN','ACKNOWLEDGED')"),
    )
    op.drop_index("ix_alerts_status", table_name="alerts")
    op.drop_index("ix_alerts_page", table_name="alerts")
    op.drop_index("ix_alerts_mission", table_name="alerts")
    op.drop_table("alerts")
    # ### end Alembic commands ###
