"""execution"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0005_execution"
down_revision = "0004_alerts_history"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "approvals",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("plan_id", sa.String(length=128), nullable=False),
        sa.Column("actor_id", sa.String(length=128), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("proposal_hash", sa.String(length=71), nullable=False),
        sa.Column("state_version", sa.BigInteger(), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("decision IN ('approve','reject')", name=op.f("ck_approvals_decision")),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plans.id"],
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approvals")),
        sa.UniqueConstraint("plan_id", name=op.f("uq_approvals_plan_id")),
    )
    op.create_table(
        "actions",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("store_id", sa.String(length=128), nullable=False),
        sa.Column("mission_id", sa.String(length=128), nullable=False),
        sa.Column("plan_id", sa.String(length=128), nullable=False),
        sa.Column("approval_id", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("purchase_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("request_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reserved_minor", sa.BigInteger(), nullable=False),
        sa.Column("execution_state_version", sa.BigInteger(), nullable=True),
        sa.Column("external_order_id", sa.String(length=128), nullable=True),
        sa.Column("receipt", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("last_error", sa.String(length=128), nullable=True),
        sa.Column("manual_review", sa.Boolean(), nullable=False),
        sa.Column("reconcile_count", sa.BigInteger(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('QUEUED','EXECUTING','SUCCEEDED','FAILED','UNKNOWN','STALE','CANCELLED')",
            name=op.f("ck_actions_status"),
        ),
        sa.CheckConstraint(
            "reserved_minor >= 0 AND reconcile_count >= 0", name=op.f("ck_actions_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["approval_id"],
            ["approvals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["missions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plans.id"],
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_actions")),
        sa.UniqueConstraint("approval_id", name=op.f("uq_actions_approval_id")),
        sa.UniqueConstraint("plan_id", name=op.f("uq_actions_plan_id")),
    )
    op.create_index("ix_actions_mission", "actions", ["mission_id"], unique=False)
    op.create_index("ix_actions_recovery", "actions", ["status", "next_attempt_at"], unique=False)
    op.create_table(
        "action_evidence",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("action_id", sa.String(length=128), nullable=False),
        sa.Column("document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["action_id"],
            ["actions.id"],
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_action_evidence")),
    )
    op.create_index(
        op.f("ix_action_evidence_action_id"), "action_evidence", ["action_id"], unique=False
    )
    op.add_column("stores", sa.Column("active_action_id", sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stores", "active_action_id")
    op.drop_index(op.f("ix_action_evidence_action_id"), table_name="action_evidence")
    op.drop_table("action_evidence")
    op.drop_index("ix_actions_recovery", table_name="actions")
    op.drop_index("ix_actions_mission", table_name="actions")
    op.drop_table("actions")
    op.drop_table("approvals")
    # ### end Alembic commands ###
