"""Persistent agent conversations, runs, receipts and scoped knowledge."""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0007_agent"
down_revision = "0006_periodic"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_conversations",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("principal_id", sa.String(length=128), nullable=False),
        sa.Column("mission_id", sa.String(length=128), nullable=False),
        sa.Column("store_id", sa.String(length=128), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("active_run_id", sa.String(length=128), nullable=True),
        sa.Column("next_seq", sa.BigInteger(), nullable=False),
        sa.Column("followup_enabled", sa.Boolean(), nullable=False),
        sa.Column("followup_interval", sa.BigInteger(), nullable=False),
        sa.Column("followup_version", sa.BigInteger(), nullable=False),
        sa.Column("next_due", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("consumed_trigger", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["missions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_conversations")),
    )
    op.create_index(
        "uq_agent_default",
        "agent_conversations",
        ["principal_id", "mission_id"],
        unique=True,
        postgresql_where=sa.text("is_default"),
    )
    op.create_table(
        "agent_runs",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("conversation_id", sa.String(length=128), nullable=False),
        sa.Column("input_through_seq", sa.BigInteger(), nullable=False),
        sa.Column("trigger", sa.String(length=24), nullable=False),
        sa.Column("trigger_watermark", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("job_id", sa.String(length=128), nullable=True),
        sa.Column("graph_version", sa.String(length=40), nullable=False),
        sa.Column("resume_value", sa.Text(), nullable=True),
        sa.Column("interrupt_id", sa.String(length=128), nullable=True),
        sa.Column("question", sa.Text(), nullable=True),
        sa.Column("token_hash", sa.String(length=64), nullable=True),
        sa.Column("token_job_lease", sa.String(length=128), nullable=True),
        sa.Column("output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_code", sa.String(length=80), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["agent_conversations.id"],
        ),
        sa.ForeignKeyConstraint(["job_id"], ["job_runs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_runs")),
    )
    op.create_index(
        op.f("ix_agent_runs_conversation_id"), "agent_runs", ["conversation_id"], unique=False
    )
    op.create_table(
        "agent_messages",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("conversation_id", sa.String(length=128), nullable=False),
        sa.Column("seq", sa.BigInteger(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("run_id", sa.String(length=128), nullable=True),
        sa.Column("references", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["agent_conversations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_messages")),
        sa.UniqueConstraint(
            "conversation_id", "seq", name=op.f("uq_agent_messages_conversation_id")
        ),
    )
    op.create_index(
        "uq_agent_final",
        "agent_messages",
        ["run_id"],
        unique=True,
        postgresql_where=sa.text("role = 'assistant'"),
    )
    op.create_table(
        "agent_receipts",
        sa.Column("owner", sa.String(length=256), nullable=False),
        sa.Column("key", sa.String(length=256), nullable=False),
        sa.Column("args_hash", sa.String(length=64), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("owner", "key", name=op.f("pk_agent_receipts")),
    )
    op.create_table(
        "agent_tool_calls",
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("invocation_id", sa.String(length=256), nullable=False),
        sa.Column("tool", sa.String(length=64), nullable=False),
        sa.Column("args_hash", sa.String(length=64), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.id"],
        ),
        sa.PrimaryKeyConstraint("run_id", "invocation_id", name=op.f("pk_agent_tool_calls")),
    )
    op.create_table(
        "agent_triggers",
        sa.Column("seq", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("conversation_id", sa.String(length=128), nullable=False),
        sa.Column("source_key", sa.String(length=256), nullable=False),
        sa.Column("references", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["agent_conversations.id"],
        ),
        sa.PrimaryKeyConstraint("seq", name=op.f("pk_agent_triggers")),
        sa.UniqueConstraint(
            "conversation_id", "source_key", name=op.f("uq_agent_triggers_conversation_id")
        ),
    )
    op.create_table(
        "agent_knowledge_scopes",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("principal_id", sa.String(length=128), nullable=False),
        sa.Column("store_id", sa.String(length=128), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("task_type", sa.String(length=80), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("entries", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_knowledge_scopes")),
        sa.UniqueConstraint(
            "principal_id",
            "store_id",
            "kind",
            "task_type",
            name=op.f("uq_agent_knowledge_scopes_principal_id"),
        ),
    )
    op.create_table(
        "agent_knowledge_revisions",
        sa.Column("scope_id", sa.String(length=64), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column("entries", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["scope_id"],
            ["agent_knowledge_scopes.id"],
        ),
        sa.PrimaryKeyConstraint("scope_id", "version", name=op.f("pk_agent_knowledge_revisions")),
    )
    # ### end Alembic commands ###
    op.execute("CREATE SCHEMA IF NOT EXISTS agent_checkpoints")


def downgrade():
    op.drop_table("agent_knowledge_revisions")
    op.drop_table("agent_knowledge_scopes")
    op.drop_table("agent_triggers")
    op.drop_table("agent_tool_calls")
    op.drop_table("agent_receipts")
    op.drop_table("agent_messages")
    op.drop_table("agent_runs")
    op.drop_table("agent_conversations")
